using Kasane2D.Input.Enums;
using Microsoft.Xna.Framework.Input;

namespace Kasane2D.MonoGame.Input;

internal static class Extensions
{
    public static KeyKind ToKeyKind(this Keys key)
    {
        return key switch
        {
            Keys.A => KeyKind.A,
            Keys.B => KeyKind.B,
            Keys.C => KeyKind.C,
            Keys.D => KeyKind.D,
            Keys.E => KeyKind.E,
            Keys.F => KeyKind.F,
            Keys.G => KeyKind.G,
            Keys.H => KeyKind.H,
            Keys.I => KeyKind.I,
            Keys.J => KeyKind.J,
            Keys.K => KeyKind.K,
            Keys.L => KeyKind.L,
            Keys.M => KeyKind.M,
            Keys.N => KeyKind.N,
            Keys.O => KeyKind.O,
            Keys.P => KeyKind.P,
            Keys.Q => KeyKind.Q,
            Keys.R => KeyKind.R,
            Keys.S => KeyKind.S,
            Keys.T => KeyKind.T,
            Keys.U => KeyKind.U,
            Keys.V => KeyKind.V,
            Keys.W => KeyKind.W,
            Keys.X => KeyKind.X,
            Keys.Y => KeyKind.Y,
            Keys.Z => KeyKind.Z,
            Keys.D0 => KeyKind.N0,
            Keys.D1 => KeyKind.N1,
            Keys.D2 => KeyKind.N2,
            Keys.D3 => KeyKind.N3,
            Keys.D4 => KeyKind.N4,
            Keys.D5 => KeyKind.N5,
            Keys.D6 => KeyKind.N6,
            Keys.D7 => KeyKind.N7,
            Keys.D8 => KeyKind.N8,
            Keys.D9 => KeyKind.N9,
            Keys.NumPad0 => KeyKind.Numpad0,
            Keys.NumPad1 => KeyKind.Numpad1,
            Keys.NumPad2 => KeyKind.Numpad2,
            Keys.NumPad3 => KeyKind.Numpad3,
            Keys.NumPad4 => KeyKind.Numpad4,
            Keys.NumPad5 => KeyKind.Numpad5,
            Keys.NumPad6 => KeyKind.Numpad6,
            Keys.NumPad7 => KeyKind.Numpad7,
            Keys.NumPad8 => KeyKind.Numpad8,
            Keys.NumPad9 => KeyKind.Numpad9,
            Keys.F1 => KeyKind.F1,
            Keys.F2 => KeyKind.F2,
            Keys.F3 => KeyKind.F3,
            Keys.F4 => KeyKind.F4,
            Keys.F5 => KeyKind.F5,
            Keys.F6 => KeyKind.F6,
            Keys.F7 => KeyKind.F7,
            Keys.F8 => KeyKind.F8,
            Keys.F9 => KeyKind.F9,
            Keys.F10 => KeyKind.F10,
            Keys.F11 => KeyKind.F11,
            Keys.F12 => KeyKind.F12,
            Keys.OemComma => KeyKind.Comma,
            Keys.OemPeriod => KeyKind.Period,
            Keys.OemQuestion => KeyKind.QuestionMark,
            Keys.OemSemicolon => KeyKind.Semicolon,
            Keys.OemQuotes => KeyKind.Quote,
            Keys.OemOpenBrackets => KeyKind.BracketOpen,
            Keys.OemCloseBrackets => KeyKind.BracketClose,
            Keys.OemPipe => KeyKind.Backslash,
            Keys.OemMinus => KeyKind.Minus,
            Keys.OemPlus => KeyKind.Plus,
            Keys.Tab => KeyKind.Tab,
            Keys.Escape => KeyKind.Escape,
            Keys.Enter => KeyKind.Enter,
            Keys.Back => KeyKind.Backspace,
            Keys.Delete => KeyKind.Delete,
            Keys.Space => KeyKind.Space,
            Keys.Up => KeyKind.Up,
            Keys.Down => KeyKind.Down,
            Keys.Left => KeyKind.Left,
            Keys.Right => KeyKind.Right,
            Keys.LeftControl => KeyKind.LeftCtrl,
            Keys.LeftAlt => KeyKind.LeftAlt,
            Keys.LeftShift => KeyKind.LeftShift,
            Keys.RightControl => KeyKind.RightCtrl,
            Keys.RightAlt => KeyKind.RightAlt,
            Keys.RightShift => KeyKind.RightShift,
            _ => KeyKind.Undefined,
        };
    }

    public static Keys ToKeys(this KeyKind kind)
    {
        return kind switch
        {
            KeyKind.A => Keys.A,
            KeyKind.B => Keys.B,
            KeyKind.C => Keys.C,
            KeyKind.D => Keys.D,
            KeyKind.E => Keys.E,
            KeyKind.F => Keys.F,
            KeyKind.G => Keys.G,
            KeyKind.H => Keys.H,
            KeyKind.I => Keys.I,
            KeyKind.J => Keys.J,
            KeyKind.K => Keys.K,
            KeyKind.L => Keys.L,
            KeyKind.M => Keys.M,
            KeyKind.N => Keys.N,
            KeyKind.O => Keys.O,
            KeyKind.P => Keys.P,
            KeyKind.Q => Keys.Q,
            KeyKind.R => Keys.R,
            KeyKind.S => Keys.S,
            KeyKind.T => Keys.T,
            KeyKind.U => Keys.U,
            KeyKind.V => Keys.V,
            KeyKind.W => Keys.W,
            KeyKind.X => Keys.X,
            KeyKind.Y => Keys.Y,
            KeyKind.Z => Keys.Z,
            KeyKind.N0 => Keys.D0,
            KeyKind.N1 => Keys.D1,
            KeyKind.N2 => Keys.D2,
            KeyKind.N3 => Keys.D3,
            KeyKind.N4 => Keys.D4,
            KeyKind.N5 => Keys.D5,
            KeyKind.N6 => Keys.D6,
            KeyKind.N7 => Keys.D7,
            KeyKind.N8 => Keys.D8,
            KeyKind.N9 => Keys.D9,
            KeyKind.Numpad0 => Keys.NumPad0,
            KeyKind.Numpad1 => Keys.NumPad1,
            KeyKind.Numpad2 => Keys.NumPad2,
            KeyKind.Numpad3 => Keys.NumPad3,
            KeyKind.Numpad4 => Keys.NumPad4,
            KeyKind.Numpad5 => Keys.NumPad5,
            KeyKind.Numpad6 => Keys.NumPad6,
            KeyKind.Numpad7 => Keys.NumPad7,
            KeyKind.Numpad8 => Keys.NumPad8,
            KeyKind.Numpad9 => Keys.NumPad9,
            KeyKind.F1 => Keys.F1,
            KeyKind.F2 => Keys.F2,
            KeyKind.F3 => Keys.F3,
            KeyKind.F4 => Keys.F4,
            KeyKind.F5 => Keys.F5,
            KeyKind.F6 => Keys.F6,
            KeyKind.F7 => Keys.F7,
            KeyKind.F8 => Keys.F8,
            KeyKind.F9 => Keys.F9,
            KeyKind.F10 => Keys.F10,
            KeyKind.F11 => Keys.F11,
            KeyKind.F12 => Keys.F12,
            KeyKind.Comma => Keys.OemComma,
            KeyKind.Period => Keys.OemPeriod,
            KeyKind.QuestionMark => Keys.OemQuestion,
            KeyKind.Semicolon => Keys.OemSemicolon,
            KeyKind.Quote => Keys.OemQuotes,
            KeyKind.BracketOpen => Keys.OemOpenBrackets,
            KeyKind.BracketClose => Keys.OemCloseBrackets,
            KeyKind.Backslash => Keys.OemPipe,
            KeyKind.Minus => Keys.OemMinus,
            KeyKind.Plus => Keys.OemPlus,
            KeyKind.Tab => Keys.Tab,
            KeyKind.Escape => Keys.Escape,
            KeyKind.Enter => Keys.Enter,
            KeyKind.Backspace => Keys.Back,
            KeyKind.Delete => Keys.Delete,
            KeyKind.Space => Keys.Space,
            KeyKind.Up => Keys.Up,
            KeyKind.Down => Keys.Down,
            KeyKind.Left => Keys.Left,
            KeyKind.Right => Keys.Right,
            KeyKind.LeftCtrl => Keys.LeftControl,
            KeyKind.LeftAlt => Keys.LeftAlt,
            KeyKind.LeftShift => Keys.LeftShift,
            KeyKind.RightCtrl => Keys.RightControl,
            KeyKind.RightAlt => Keys.RightAlt,
            KeyKind.RightShift => Keys.RightShift,
            _ => Keys.None,
        };
    }
}