<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <IsPackable>true</IsPackable>
        <PackageId>Kasane2D</PackageId>
        <Version>1.0.0-rc.1</Version>
        <Authors>Emynator</Authors>
        <Description>
            Code-first 2D game engine for .NET with retro-inspired rendering,
            modern audio mixing, and explicit developer control.
        </Description>
        <PackageTags>
            game-engine;2d;gamedev;csharp;dotnet;retro;tilemap;sprites;audio
        </PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © 2026 Emynator</Copyright>
        <RepositoryUrl>https://github.com/Emynator/Kasane2D</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/Emynator/Kasane2D</PackageProjectUrl>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
      <None Include="Readme.md" Pack="true" PackagePath="\" />
      <Folder Include="Sound\AudioEffects\" />
    </ItemGroup>

</Project>
